# app/crud/tasks.py
from typing import Any, Optional, Sequence

from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.task_model import Task
from app.schemas.taskbase import TaskCreate, TaskUpdate


async def create_task(db: AsyncSession, task: TaskCreate):
    """
    Creates a new task in the database asynchronously.

    Args:
        db: The asynchronous SQLAlchemy session object.
        task: The Pydantic schema with task data.

    Returns:
        The created task object from the DB, or None on error.
    """
    try:
        # Create an instance of the SQLAlchemy model from the Pydantic data.
        db_task = Task(**task.model_dump())

        # Add the object to the session.
        db.add(db_task)

        # Commit the transaction to save the object to the DB.
        # This is an awaited operation.
        await db.commit()

        # Refresh the object to get the ID generated by the DB.
        # This is an awaited operation.
        await db.refresh(db_task)

        return db_task
    except SQLAlchemyError as e:
        print(f"Database error during task creation: {e}")
        # Rollback the transaction on error.
        await db.rollback()
        return None


async def get_tasks(
    db: AsyncSession, completed: Optional[bool] = None
) -> Sequence[Task] | list[Any]:
    """
    Retrieves all tasks from the database asynchronously.

    Args:
        db: The asynchronous SQLAlchemy session object.
        completed: Optional filter to retrieve only completed or uncompleted tasks.

    Returns:
        A list of task objects.
    """
    try:
        # Build the initial query
        query = select(Task)

        # Add filtering if the 'completed' parameter is provided
        if completed is not None:
            query = query.where(Task.completed == completed)

        # Execute the query asynchronously and get all results
        result = await db.execute(query)

        # Return all tasks from the result
        return result.scalars().all()
    except SQLAlchemyError as e:
        print(f"Database error during task retrieval: {e}")
        return []


async def get_task_by_id(task_id: int, db: AsyncSession):
    """
    Retrieves a single task by its ID asynchronously.

    Args:
        db: The asynchronous SQLAlchemy session object.
        task_id: The ID of the task.

    Returns:
        The task object or None if the task is not found.
    """
    try:
        # Build the query to select a single task by ID
        query = select(Task).where(Task.id == task_id)

        # Execute the query asynchronously
        result = await db.execute(query)

        # Get the first result from the scalar results
        return result.scalars().first()
    except SQLAlchemyError as e:
        print(f"Database error during task retrieval by ID: {e}")
        return None


async def update_task(
    task_id: int,
    task_data: TaskUpdate,
    db: AsyncSession,
):
    """
    Updates an existing task asynchronously.

    Args:
        db: The asynchronous SQLAlchemy session object.
        task_id: The ID of the task to update.
        task_data: The Pydantic schema with the updated data.

    Returns:
        The updated task object or None if the task is not found.
    """
    try:
        # First, find the task to be updated
        db_task = await get_task_by_id(task_id=task_id, db=db)
        if not db_task:
            return None

        # Update the fields using .model_dump() with exclude_unset=True
        for key, value in task_data.model_dump(exclude_unset=True).items():
            setattr(db_task, key, value)

        # Commit the changes to the database
        await db.commit()
        await db.refresh(db_task)

        return db_task
    except SQLAlchemyError as e:
        print(f"Database error during task update id: {task_id}: {e}")
        # Rollback on error
        await db.rollback()
        return None


async def delete_task(task_id: int, db: AsyncSession):
    """
    Deletes a task from the database asynchronously.

    Args:
        db: The asynchronous SQLAlchemy session object.
        task_id: The ID of the task to delete.

    Returns:
        The deleted task object or None if the task is not found.
    """
    try:
        # Find the task to delete
        db_task = await get_task_by_id(task_id=task_id, db=db)
        if not db_task:
            return None

        # Delete the task
        await db.delete(db_task)
        await db.commit()

        return db_task
    except SQLAlchemyError as e:
        # If any database error occurs, print a message and rollback the transaction
        print(f"Database error during task deletion: {e}")
        await db.rollback()
        return None
